name: dart_shp
description: An shapefile reader/writer for dart.
version: 0.0.1
homepage: https://www.hydrologis.com
repository: https://github.com/moovida/dart_shp
issue_tracker: https://github.com/moovida/dart_shp/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
 path: ^1.6.0
 # APACHE 2.0
 chunked_stream: ^1.1.0
 # MIT
 logger: ^0.8.3
 #BSD
 dart_jts: ^0.0.5+2
 # BSD
 timezone: ^0.5.7
 # BSD
 characters: ^0.5.0


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
